linters:
  disable-all: true
  enable:
    - deadcode
    - gocyclo
    # - revive TODO: Fix revive lint #175
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - errcheck
    - unused
    - gosimple
    - varcheck

linters-settings:
  gofmt:
    simplify: false
  gosec:
    excludes:
    - G306 # G306: Expect WriteFile permissions to be 0600 or less

run:
  timeout: 5m
