version: 2.1
jobs:
  test:
    docker:
      - image: golang:1.16-buster
    steps:
      - checkout
      - restore_cache:
          key: likecoin-chain-{{ checksum "go.mod" }}
      - run:
          name: Dependencies
          command: make go-mod-cache
      - save_cache:
          key: likecoin-chain-{{ checksum "go.mod" }}
          paths: /go/pkg
      - run:
          name: Install golint
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.44.0
      - run:
          name: Lint
          command: make lint
      - run:
          name: Test
          command: make test
  build:
    docker:
      - image: golang:1.16-buster
    steps:
      - checkout
      - run:
          name: Build
          command: make build
      - store_artifacts:
          path: /root/project/build
  deploy:
    docker:
      - image: golang:1.16-buster
    steps:
      - run:
          name: Test
          command: go test -timeout 5m ./...

      # Handle deployment

workflows:
  version: 2.1
  test_and_build:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - develop
