// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: likechain/likenft/class_input.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ClassInput struct {
	Name        string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Symbol      string      `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Description string      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Uri         string      `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	UriHash     string      `protobuf:"bytes,5,opt,name=uri_hash,json=uriHash,proto3" json:"uri_hash,omitempty"`
	Metadata    JsonInput   `protobuf:"bytes,6,opt,name=metadata,proto3,customtype=JsonInput" json:"metadata"`
	Config      ClassConfig `protobuf:"bytes,7,opt,name=config,proto3" json:"config"`
}

func (m *ClassInput) Reset()         { *m = ClassInput{} }
func (m *ClassInput) String() string { return proto.CompactTextString(m) }
func (*ClassInput) ProtoMessage()    {}
func (*ClassInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_6776761e72dfe280, []int{0}
}
func (m *ClassInput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClassInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClassInput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClassInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassInput.Merge(m, src)
}
func (m *ClassInput) XXX_Size() int {
	return m.Size()
}
func (m *ClassInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassInput.DiscardUnknown(m)
}

var xxx_messageInfo_ClassInput proto.InternalMessageInfo

func (m *ClassInput) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClassInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ClassInput) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ClassInput) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *ClassInput) GetUriHash() string {
	if m != nil {
		return m.UriHash
	}
	return ""
}

func (m *ClassInput) GetConfig() ClassConfig {
	if m != nil {
		return m.Config
	}
	return ClassConfig{}
}

type ClassParentInput struct {
	Type         ClassParentType `protobuf:"varint,1,opt,name=type,proto3,enum=likechain.likenft.ClassParentType" json:"type,omitempty"`
	IscnIdPrefix string          `protobuf:"bytes,2,opt,name=iscn_id_prefix,json=iscnIdPrefix,proto3" json:"iscn_id_prefix,omitempty"`
}

func (m *ClassParentInput) Reset()         { *m = ClassParentInput{} }
func (m *ClassParentInput) String() string { return proto.CompactTextString(m) }
func (*ClassParentInput) ProtoMessage()    {}
func (*ClassParentInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_6776761e72dfe280, []int{1}
}
func (m *ClassParentInput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClassParentInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClassParentInput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClassParentInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassParentInput.Merge(m, src)
}
func (m *ClassParentInput) XXX_Size() int {
	return m.Size()
}
func (m *ClassParentInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassParentInput.DiscardUnknown(m)
}

var xxx_messageInfo_ClassParentInput proto.InternalMessageInfo

func (m *ClassParentInput) GetType() ClassParentType {
	if m != nil {
		return m.Type
	}
	return ClassParentType_UNKNOWN
}

func (m *ClassParentInput) GetIscnIdPrefix() string {
	if m != nil {
		return m.IscnIdPrefix
	}
	return ""
}

func init() {
	proto.RegisterType((*ClassInput)(nil), "likechain.likenft.ClassInput")
	proto.RegisterType((*ClassParentInput)(nil), "likechain.likenft.ClassParentInput")
}

func init() {
	proto.RegisterFile("likechain/likenft/class_input.proto", fileDescriptor_6776761e72dfe280)
}

var fileDescriptor_6776761e72dfe280 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4f, 0x8b, 0xda, 0x40,
	0x1c, 0xcd, 0xd4, 0x34, 0xea, 0x28, 0xa2, 0x43, 0x29, 0xa9, 0x87, 0x18, 0xd2, 0x8b, 0x14, 0x4c,
	0x40, 0x69, 0x4f, 0x3d, 0xe9, 0xa5, 0xf6, 0x52, 0x09, 0x3d, 0xf5, 0x12, 0xc6, 0x24, 0x26, 0x43,
	0xcd, 0x4c, 0xc8, 0x4c, 0x44, 0xbf, 0xc5, 0x7e, 0x2c, 0x8f, 0x1e, 0x97, 0x3d, 0xc8, 0xa2, 0x5f,
	0x61, 0x3f, 0xc0, 0x32, 0x93, 0x20, 0x0b, 0x8b, 0xb7, 0x37, 0xef, 0xbd, 0xf9, 0xfd, 0x7b, 0xf0,
	0xeb, 0x96, 0xfc, 0x8f, 0xc3, 0x14, 0x13, 0xea, 0x49, 0x44, 0x37, 0xc2, 0x0b, 0xb7, 0x98, 0xf3,
	0x80, 0xd0, 0xbc, 0x14, 0x6e, 0x5e, 0x30, 0xc1, 0xd0, 0xe0, 0x66, 0x72, 0x6b, 0xd3, 0xf0, 0x53,
	0xc2, 0x12, 0xa6, 0x54, 0x4f, 0xa2, 0xca, 0x38, 0x74, 0xee, 0x55, 0x8b, 0xb0, 0xc0, 0x95, 0xc7,
	0x79, 0x01, 0x10, 0x2e, 0x24, 0xb9, 0x94, 0x1d, 0x10, 0x82, 0x3a, 0xc5, 0x59, 0x6c, 0x02, 0x1b,
	0x8c, 0xdb, 0xbe, 0xc2, 0xe8, 0x33, 0x34, 0xf8, 0x21, 0x5b, 0xb3, 0xad, 0xf9, 0x41, 0xb1, 0xf5,
	0x0b, 0xd9, 0xb0, 0x13, 0xc5, 0x3c, 0x2c, 0x48, 0x2e, 0x08, 0xa3, 0x66, 0x43, 0x89, 0x6f, 0x29,
	0xd4, 0x87, 0x8d, 0xb2, 0x20, 0xa6, 0xae, 0x14, 0x09, 0xd1, 0x17, 0xd8, 0x2a, 0x0b, 0x12, 0xa4,
	0x98, 0xa7, 0xe6, 0x47, 0x45, 0x37, 0xcb, 0x82, 0xfc, 0xc2, 0x3c, 0x45, 0x13, 0xd8, 0xca, 0x62,
	0x81, 0xe5, 0x6c, 0xa6, 0x61, 0x83, 0x71, 0x77, 0x3e, 0x38, 0x9e, 0x47, 0xda, 0xd3, 0x79, 0xd4,
	0xfe, 0xcd, 0x19, 0x55, 0xf3, 0xf9, 0x37, 0x0b, 0xfa, 0x09, 0x8d, 0x90, 0xd1, 0x0d, 0x49, 0xcc,
	0xa6, 0x0d, 0xc6, 0x9d, 0xa9, 0xe5, 0xbe, 0x3b, 0x8b, 0xab, 0x16, 0x5b, 0x28, 0xd7, 0x5c, 0x97,
	0xc5, 0xfc, 0xfa, 0x8f, 0xb3, 0x83, 0x7d, 0x25, 0xae, 0x70, 0x11, 0x53, 0x51, 0xed, 0xfe, 0x03,
	0xea, 0xe2, 0x90, 0x57, 0xbb, 0xf7, 0xa6, 0xce, 0xbd, 0x7a, 0xd5, 0x97, 0xbf, 0x87, 0x3c, 0xf6,
	0x95, 0x1f, 0x7d, 0x83, 0x3d, 0xc2, 0x43, 0x1a, 0x90, 0x28, 0xc8, 0x8b, 0x78, 0x43, 0xf6, 0xd5,
	0x9d, 0x54, 0x47, 0xe0, 0x77, 0xa5, 0xb6, 0x8c, 0x56, 0x4a, 0x99, 0xff, 0x39, 0x5e, 0x2c, 0x70,
	0xba, 0x58, 0xe0, 0xf9, 0x62, 0x81, 0x87, 0xab, 0xa5, 0x9d, 0xae, 0x96, 0xf6, 0x78, 0xb5, 0xb4,
	0x7f, 0xdf, 0x13, 0x22, 0xd2, 0x72, 0xed, 0x86, 0x2c, 0x53, 0x69, 0x85, 0xac, 0x8e, 0x4d, 0x82,
	0x49, 0x95, 0xe2, 0x6e, 0xe6, 0xed, 0x6f, 0x51, 0xca, 0xde, 0x7c, 0x6d, 0xa8, 0x18, 0x67, 0xaf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x47, 0x16, 0xf9, 0x3a, 0x02, 0x00, 0x00,
}

func (m *ClassInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClassInput) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClassInput) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Config.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClassInput(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.Metadata.Size()
		i -= size
		if _, err := m.Metadata.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintClassInput(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.UriHash) > 0 {
		i -= len(m.UriHash)
		copy(dAtA[i:], m.UriHash)
		i = encodeVarintClassInput(dAtA, i, uint64(len(m.UriHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Uri) > 0 {
		i -= len(m.Uri)
		copy(dAtA[i:], m.Uri)
		i = encodeVarintClassInput(dAtA, i, uint64(len(m.Uri)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintClassInput(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintClassInput(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintClassInput(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ClassParentInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClassParentInput) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClassParentInput) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IscnIdPrefix) > 0 {
		i -= len(m.IscnIdPrefix)
		copy(dAtA[i:], m.IscnIdPrefix)
		i = encodeVarintClassInput(dAtA, i, uint64(len(m.IscnIdPrefix)))
		i--
		dAtA[i] = 0x12
	}
	if m.Type != 0 {
		i = encodeVarintClassInput(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintClassInput(dAtA []byte, offset int, v uint64) int {
	offset -= sovClassInput(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ClassInput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovClassInput(uint64(l))
	}
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovClassInput(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovClassInput(uint64(l))
	}
	l = len(m.Uri)
	if l > 0 {
		n += 1 + l + sovClassInput(uint64(l))
	}
	l = len(m.UriHash)
	if l > 0 {
		n += 1 + l + sovClassInput(uint64(l))
	}
	l = m.Metadata.Size()
	n += 1 + l + sovClassInput(uint64(l))
	l = m.Config.Size()
	n += 1 + l + sovClassInput(uint64(l))
	return n
}

func (m *ClassParentInput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovClassInput(uint64(m.Type))
	}
	l = len(m.IscnIdPrefix)
	if l > 0 {
		n += 1 + l + sovClassInput(uint64(l))
	}
	return n
}

func sovClassInput(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozClassInput(x uint64) (n int) {
	return sovClassInput(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClassInput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClassInput
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClassInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClassInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassInput
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClassInput
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClassInput
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassInput
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClassInput
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClassInput
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassInput
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClassInput
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClassInput
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassInput
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClassInput
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClassInput
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UriHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassInput
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClassInput
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClassInput
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UriHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassInput
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClassInput
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClassInput
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassInput
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClassInput
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClassInput
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Config.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClassInput(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClassInput
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClassParentInput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClassInput
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClassParentInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClassParentInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassInput
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= ClassParentType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IscnIdPrefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassInput
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClassInput
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClassInput
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IscnIdPrefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClassInput(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClassInput
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClassInput(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClassInput
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClassInput
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClassInput
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthClassInput
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupClassInput
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthClassInput
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthClassInput        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClassInput          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupClassInput = fmt.Errorf("proto: unexpected end of group")
)
