// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: likechain/likenft/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the likenft module's genesis state.
type GenesisState struct {
	Params                   Params                    `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	ClassesByIscnList        []ClassesByISCN           `protobuf:"bytes,2,rep,name=classes_by_iscn_list,json=classesByIscnList,proto3" json:"classes_by_iscn_list"`
	ClassesByAccountList     []ClassesByAccount        `protobuf:"bytes,3,rep,name=classes_by_account_list,json=classesByAccountList,proto3" json:"classes_by_account_list"`
	BlindBoxContentList      []BlindBoxContent         `protobuf:"bytes,4,rep,name=blind_box_content_list,json=blindBoxContentList,proto3" json:"blind_box_content_list"`
	ClassRevealQueue         []ClassRevealQueueEntry   `protobuf:"bytes,5,rep,name=class_reveal_queue,json=classRevealQueue,proto3" json:"class_reveal_queue"`
	OfferList                []Offer                   `protobuf:"bytes,6,rep,name=offer_list,json=offerList,proto3" json:"offer_list"`
	ListingList              []Listing                 `protobuf:"bytes,7,rep,name=listing_list,json=listingList,proto3" json:"listing_list"`
	OfferExpireQueue         []OfferExpireQueueEntry   `protobuf:"bytes,8,rep,name=offer_expire_queue,json=offerExpireQueue,proto3" json:"offer_expire_queue"`
	ListingExpireQueue       []ListingExpireQueueEntry `protobuf:"bytes,9,rep,name=listing_expire_queue,json=listingExpireQueue,proto3" json:"listing_expire_queue"`
	RoyaltyConfigByClassList []RoyaltyConfigByClass    `protobuf:"bytes,10,rep,name=royalty_config_by_class_list,json=royaltyConfigByClassList,proto3" json:"royalty_config_by_class_list"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae2e28366593bfc, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetClassesByIscnList() []ClassesByISCN {
	if m != nil {
		return m.ClassesByIscnList
	}
	return nil
}

func (m *GenesisState) GetClassesByAccountList() []ClassesByAccount {
	if m != nil {
		return m.ClassesByAccountList
	}
	return nil
}

func (m *GenesisState) GetBlindBoxContentList() []BlindBoxContent {
	if m != nil {
		return m.BlindBoxContentList
	}
	return nil
}

func (m *GenesisState) GetClassRevealQueue() []ClassRevealQueueEntry {
	if m != nil {
		return m.ClassRevealQueue
	}
	return nil
}

func (m *GenesisState) GetOfferList() []Offer {
	if m != nil {
		return m.OfferList
	}
	return nil
}

func (m *GenesisState) GetListingList() []Listing {
	if m != nil {
		return m.ListingList
	}
	return nil
}

func (m *GenesisState) GetOfferExpireQueue() []OfferExpireQueueEntry {
	if m != nil {
		return m.OfferExpireQueue
	}
	return nil
}

func (m *GenesisState) GetListingExpireQueue() []ListingExpireQueueEntry {
	if m != nil {
		return m.ListingExpireQueue
	}
	return nil
}

func (m *GenesisState) GetRoyaltyConfigByClassList() []RoyaltyConfigByClass {
	if m != nil {
		return m.RoyaltyConfigByClassList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "likechain.likenft.GenesisState")
}

func init() { proto.RegisterFile("likechain/likenft/genesis.proto", fileDescriptor_fae2e28366593bfc) }

var fileDescriptor_fae2e28366593bfc = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x80, 0x1b, 0x36, 0x0a, 0x73, 0x77, 0x60, 0xa1, 0x82, 0x50, 0x41, 0x56, 0x0d, 0x89, 0x95,
	0x09, 0x52, 0x69, 0x13, 0xe2, 0xc4, 0x81, 0x44, 0x13, 0x42, 0x9a, 0x18, 0x74, 0x07, 0x24, 0x04,
	0x0a, 0x89, 0x71, 0x33, 0x8b, 0xd4, 0x2e, 0xb1, 0x3b, 0x35, 0xff, 0x82, 0x9f, 0xb5, 0xe3, 0x8e,
	0x9c, 0x10, 0x6a, 0xff, 0x02, 0x3f, 0x00, 0xf9, 0xd9, 0xab, 0xd4, 0x3a, 0x29, 0xb7, 0x28, 0xef,
	0xf3, 0xf7, 0x9e, 0xfd, 0xde, 0x43, 0xbb, 0x39, 0xfd, 0x4e, 0xf0, 0x79, 0x42, 0x59, 0x5f, 0x7d,
	0xb1, 0xa1, 0xec, 0x67, 0x84, 0x11, 0x41, 0x45, 0x30, 0x2e, 0xb8, 0xe4, 0xee, 0xce, 0x02, 0x08,
	0x0c, 0xd0, 0x69, 0x67, 0x3c, 0xe3, 0x10, 0xed, 0xab, 0x2f, 0x0d, 0x76, 0x9e, 0xda, 0xa6, 0x34,
	0xa7, 0xec, 0x5b, 0x9c, 0xf2, 0x69, 0x8c, 0x39, 0x93, 0x84, 0x49, 0x83, 0x1e, 0xd8, 0x28, 0xce,
	0x13, 0x21, 0xe2, 0x82, 0x5c, 0x90, 0x24, 0x8f, 0x7f, 0x4c, 0xc8, 0x84, 0xfc, 0x87, 0x25, 0x22,
	0x4e, 0xcb, 0x38, 0xc1, 0x98, 0x4f, 0x16, 0xde, 0xfd, 0xb5, 0x2c, 0x15, 0x98, 0x19, 0xb0, 0xe2,
	0xd6, 0x39, 0x15, 0x92, 0xb2, 0xcc, 0x00, 0xcf, 0x6a, 0x81, 0x98, 0x4c, 0xc7, 0xb4, 0x20, 0x4b,
	0x35, 0x3e, 0xb2, 0x69, 0x3e, 0x1c, 0x92, 0xa2, 0xfe, 0x0a, 0x10, 0xae, 0x52, 0xf9, 0x36, 0x3b,
	0x4e, 0x8a, 0x64, 0x64, 0xda, 0xd1, 0x79, 0x62, 0xc7, 0x0b, 0x5e, 0x26, 0xb9, 0x2c, 0xd5, 0x1b,
	0x0f, 0xa9, 0xb9, 0xc0, 0xde, 0xdf, 0x26, 0xda, 0x7e, 0xa3, 0x1b, 0x79, 0x26, 0x13, 0x49, 0xdc,
	0x97, 0xa8, 0xa9, 0x45, 0x9e, 0xd3, 0x75, 0x7a, 0xad, 0xc3, 0x07, 0x81, 0xd5, 0xd8, 0xe0, 0x3d,
	0x00, 0xe1, 0xe6, 0xe5, 0xef, 0xdd, 0xc6, 0xc0, 0xe0, 0xee, 0x47, 0xd4, 0x5e, 0x79, 0xc4, 0x58,
	0x3d, 0x85, 0x77, 0xa3, 0xbb, 0xd1, 0x6b, 0x1d, 0x76, 0x2b, 0x34, 0x91, 0xc6, 0xc3, 0xf2, 0xed,
	0x59, 0xf4, 0xce, 0xd8, 0x76, 0xf0, 0xe2, 0xa7, 0xc0, 0xec, 0x84, 0x0a, 0xe9, 0x7e, 0x45, 0xf7,
	0xed, 0x4e, 0x6a, 0xf7, 0x06, 0xb8, 0x1f, 0xaf, 0x73, 0xbf, 0xd6, 0xbc, 0xd1, 0xb7, 0xf1, 0xca,
	0x7f, 0xc8, 0xf0, 0x05, 0xdd, 0xb3, 0x46, 0x50, 0x27, 0xd8, 0x84, 0x04, 0x7b, 0x15, 0x09, 0x42,
	0x75, 0x20, 0xe4, 0xd3, 0x48, 0xe3, 0xc6, 0x7f, 0x37, 0x5d, 0xfe, 0x0d, 0xfa, 0xcf, 0xc8, 0xb5,
	0xc7, 0xd6, 0xbb, 0x09, 0xea, 0x5e, 0x5d, 0xed, 0x03, 0x60, 0x3f, 0x28, 0xf4, 0x98, 0xc9, 0xa2,
	0x34, 0x09, 0xee, 0xe0, 0x95, 0xa0, 0xfb, 0x0a, 0x21, 0x3d, 0x25, 0x50, 0x70, 0x13, 0xac, 0x5e,
	0x85, 0xf5, 0x54, 0x41, 0xc6, 0xb2, 0x05, 0x27, 0xa0, 0xb8, 0x08, 0x6d, 0x5f, 0x4f, 0x2c, 0x08,
	0x6e, 0x81, 0xa0, 0x53, 0x21, 0x38, 0xd1, 0x98, 0x51, 0xb4, 0xcc, 0xa9, 0xeb, 0x1b, 0xda, 0x93,
	0xea, 0xdd, 0xae, 0xbd, 0x21, 0xd4, 0x72, 0x0c, 0xac, 0x7d, 0x43, 0xbe, 0x12, 0x74, 0x53, 0xd4,
	0xae, 0x5a, 0x2a, 0x6f, 0x0b, 0xfc, 0x07, 0xf5, 0xa5, 0xd6, 0x64, 0x70, 0x73, 0x2b, 0xec, 0x8e,
	0xd0, 0xc3, 0xe5, 0xfd, 0x50, 0xb3, 0xa6, 0xbb, 0x06, 0xcf, 0x82, 0x20, 0xd7, 0x7e, 0x45, 0xae,
	0x81, 0x3e, 0x16, 0xc1, 0xa9, 0xb0, 0x84, 0xe6, 0x99, 0x44, 0x5e, 0x51, 0x11, 0x53, 0xb5, 0x85,
	0xa7, 0x97, 0x33, 0xdf, 0xb9, 0x9a, 0xf9, 0xce, 0x9f, 0x99, 0xef, 0xfc, 0x9c, 0xfb, 0x8d, 0xab,
	0xb9, 0xdf, 0xf8, 0x35, 0xf7, 0x1b, 0x9f, 0x5e, 0x64, 0x54, 0x9e, 0x4f, 0xd2, 0x00, 0xf3, 0x11,
	0x6c, 0x2e, 0xe6, 0x66, 0x85, 0xd5, 0xc7, 0x73, 0xbd, 0xd1, 0x17, 0x47, 0xfd, 0xe9, 0x62, 0xad,
	0x65, 0x39, 0x26, 0x22, 0x6d, 0xc2, 0x3a, 0x1f, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xde,
	0xaa, 0x30, 0xa8, 0x05, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RoyaltyConfigByClassList) > 0 {
		for iNdEx := len(m.RoyaltyConfigByClassList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RoyaltyConfigByClassList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.ListingExpireQueue) > 0 {
		for iNdEx := len(m.ListingExpireQueue) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ListingExpireQueue[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.OfferExpireQueue) > 0 {
		for iNdEx := len(m.OfferExpireQueue) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OfferExpireQueue[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.ListingList) > 0 {
		for iNdEx := len(m.ListingList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ListingList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.OfferList) > 0 {
		for iNdEx := len(m.OfferList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OfferList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.ClassRevealQueue) > 0 {
		for iNdEx := len(m.ClassRevealQueue) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ClassRevealQueue[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.BlindBoxContentList) > 0 {
		for iNdEx := len(m.BlindBoxContentList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BlindBoxContentList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ClassesByAccountList) > 0 {
		for iNdEx := len(m.ClassesByAccountList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ClassesByAccountList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ClassesByIscnList) > 0 {
		for iNdEx := len(m.ClassesByIscnList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ClassesByIscnList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.ClassesByIscnList) > 0 {
		for _, e := range m.ClassesByIscnList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ClassesByAccountList) > 0 {
		for _, e := range m.ClassesByAccountList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BlindBoxContentList) > 0 {
		for _, e := range m.BlindBoxContentList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ClassRevealQueue) > 0 {
		for _, e := range m.ClassRevealQueue {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OfferList) > 0 {
		for _, e := range m.OfferList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ListingList) > 0 {
		for _, e := range m.ListingList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OfferExpireQueue) > 0 {
		for _, e := range m.OfferExpireQueue {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ListingExpireQueue) > 0 {
		for _, e := range m.ListingExpireQueue {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RoyaltyConfigByClassList) > 0 {
		for _, e := range m.RoyaltyConfigByClassList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassesByIscnList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassesByIscnList = append(m.ClassesByIscnList, ClassesByISCN{})
			if err := m.ClassesByIscnList[len(m.ClassesByIscnList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassesByAccountList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassesByAccountList = append(m.ClassesByAccountList, ClassesByAccount{})
			if err := m.ClassesByAccountList[len(m.ClassesByAccountList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlindBoxContentList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlindBoxContentList = append(m.BlindBoxContentList, BlindBoxContent{})
			if err := m.BlindBoxContentList[len(m.BlindBoxContentList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassRevealQueue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassRevealQueue = append(m.ClassRevealQueue, ClassRevealQueueEntry{})
			if err := m.ClassRevealQueue[len(m.ClassRevealQueue)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfferList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OfferList = append(m.OfferList, Offer{})
			if err := m.OfferList[len(m.OfferList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListingList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ListingList = append(m.ListingList, Listing{})
			if err := m.ListingList[len(m.ListingList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfferExpireQueue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OfferExpireQueue = append(m.OfferExpireQueue, OfferExpireQueueEntry{})
			if err := m.OfferExpireQueue[len(m.OfferExpireQueue)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListingExpireQueue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ListingExpireQueue = append(m.ListingExpireQueue, ListingExpireQueueEntry{})
			if err := m.ListingExpireQueue[len(m.ListingExpireQueue)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoyaltyConfigByClassList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoyaltyConfigByClassList = append(m.RoyaltyConfigByClassList, RoyaltyConfigByClass{})
			if err := m.RoyaltyConfigByClassList[len(m.RoyaltyConfigByClassList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
