name: Lint Check
on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - "feat/**"
jobs:
  lint:
    name: Check lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Install golint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2
      - name: Run lint check
        run: make lint